# Generated by Django 3.2.3 on 2021-06-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_imagen_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mensaje',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
