# Generated by Django 3.2.3 on 2021-07-04 00:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_comentario_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vistas',
            field=models.ManyToManyField(blank=True, related_name='vistas', to=settings.AUTH_USER_MODEL),
        ),
    ]
