# Generated by Django 3.2.3 on 2021-07-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_vistas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='vistas',
        ),
        migrations.AddField(
            model_name='post',
            name='vistas',
            field=models.IntegerField(default=0),
        ),
    ]
