# Generated by Django 3.2.3 on 2021-07-04 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_auto_20210703_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alcance',
            field=models.ManyToManyField(blank=True, related_name='alcance', to=settings.AUTH_USER_MODEL),
        ),
    ]
