# Generated by Django 3.2.5 on 2021-07-24 00:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0014_post_alcance'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reports',
            field=models.ManyToManyField(blank=True, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
