# Generated by Django 3.2.3 on 2021-06-13 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20210613_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='user',
            name='amigos',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='user',
            name='compartido',
        ),
        migrations.RemoveField(
            model_name='user',
            name='coordenadas',
        ),
        migrations.RemoveField(
            model_name='user',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='user',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='user',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='user',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='user',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='user',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='user',
            name='movil',
        ),
        migrations.RemoveField(
            model_name='user',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='user',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='user',
            name='seguidores',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sitio_web',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tipo_usuario',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='whatsapp',
        ),
    ]
