# Generated by Django 3.2.5 on 2021-07-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='presentation',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
