# Generated by Django 3.2.5 on 2021-07-26 22:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_user_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='seguidores',
            field=models.ManyToManyField(blank=True, related_name='usuario_seguidores', to=settings.AUTH_USER_MODEL),
        ),
    ]
