# Generated by Django 3.2.3 on 2021-06-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='compartido',
            field=models.ImageField(blank=True, default=0, upload_to=''),
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='categoria',
        ),
        migrations.AddField(
            model_name='negocio',
            name='categoria',
            field=models.ManyToManyField(related_name='categoria_negocio', to='negocio.CategoriaNegocio'),
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ManyToManyField(related_name='categoria_producto', to='negocio.CategoriaProducto'),
        ),
    ]
