# Generated by Django 3.2.3 on 2021-06-15 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_auto_20210615_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='negocio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='negocio_producto', to='negocio.negocio'),
            preserve_default=False,
        ),
    ]
