# Generated by Django 3.2.3 on 2021-06-15 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0003_producto_negocio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='productos',
        ),
    ]
