# Generated by Django 3.2.3 on 2021-06-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0004_remove_negocio_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='compartido',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
