# Generated by Django 3.2.5 on 2021-08-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0005_alter_producto_compartido'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
