# Generated by Django 3.2.5 on 2021-08-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0002_emotionstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionstate',
            name='icon',
            field=models.CharField(default='../../../assets/emoticonos1-10/1-muy-mal.svg', max_length=100),
            preserve_default=False,
        ),
    ]
